name: Cache APK

on: [ workflow_dispatch ]

jobs:
  cache-apk:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: App build output cache
        uses: actions/cache@v3
        with:
          key: android-app–build-outputs-apk
          path: android/app/build/outputs/apk

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11.0.16+8'

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Build apk
        run: npx detox build --config-path ./e2e/config/.detoxrc.js --configuration android.e2e.release
