name: End to end test

on: [ workflow_dispatch ]

jobs:
  test:
    name: e2e Android staging
    runs-on: macos-12

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: App build output cache
        uses: actions/cache@v3
        with:
          key: android-app–build-outputs-apk
          path: android/app/build/outputs/apk

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-30

      - name: Test android staging
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: aosp_atd
          avd-name: e2e
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: npx detox test --config-path ./e2e/config/.detoxrc.js --configuration android.e2e.release

      - name: Upload detox artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: detox-artifacts
          path: artifacts
